acm_placement_app/placements/urls.py
from django.urls import path

from acm_placement_app.placements.views import PlacementRequestWizard, RunView, PlacementRequestList, \
    PlacementRequestDetail, download_results

app_name = 'placements'

urlpatterns = [
    path("request/", PlacementRequestWizard.as_view(), name='request-placements'),
    path("run/<int:id>/", RunView.as_view(), name='run'),
    path("list/", PlacementRequestList.as_view(), name='placementrequest-list'),
    path("<int:pk>/", PlacementRequestDetail.as_view(), name='placementrequest-details'),
    path("<int:pk>/download-results", download_results, name='placementrequest-download-results'),
]

acm_placement_app/users/urls.py
from django.urls import path

from acm_placement_app.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("acm_placement_app.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Your stuff: custom urls includes go here
urlpatterns += [
    path("placements/", include("acm_placement_app.placements.urls", namespace="placements")),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

acm_placement_app/placements/models.py
import datetime
import os

from django.conf import settings
from django.db import models
from model_utils.models import TimeStampedModel

NOT_STARTED = 'not_started'
STARTED = 'started'
FAILURE = 'failure'
SUCCESS = 'success'


def get_tomorrow_date():
    return datetime.date.today() + datetime.timedelta(days=1)


def input_upload_path(instance, filename):
    return os.path.join("data", 'inputs', filename)


def output_upload_path(instance, filename):
    return os.path.join("data", 'outputs', filename)


class PlacementRequest(TimeStampedModel, models.Model):
    requested_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    started = models.DateTimeField(blank=True, null=True, editable=False)
    completed = models.DateTimeField(blank=True, null=True, editable=False)

    @property
    def is_completed(self):
        return self.completed is not None

    @property
    def is_successful(self):
        return PlacementResult.objects.filter(placementrequest=self).exists()

    @property
    def run_duration(self):
        if self.is_completed:
            return self.completed - self.started

    @property
    def run_state(self):
        if self.started is None:
            return NOT_STARTED
        if self.started and self.completed is None:
            return STARTED
        if self.started and self.completed and not self.is_successful:
            return FAILURE
        if self.started and self.completed and self.is_successful:
            return SUCCESS

    school_data_file = models.FileField(upload_to=input_upload_path)
    acm_survey_data_file = models.FileField("ACM survey data file", upload_to=input_upload_path)

    num_iterations = models.IntegerField(
        "Number of iterations", default=10000,
        help_text="The number of team placements that will be attempted. 10,000 or more is recommended."
    )
    prevent_roommates = models.BooleanField("Prevent roommates from serving on the same team?", default=True)
    consider_HS_elig = models.BooleanField(
        "Apply High School eligibility rule?", default=True,
        help_text="ACMs are eligible to serve in High School if they are 21+ years old (or have college experience) "
                  "and are confident tutoring at least algebra-level math."
    )

    calc_commutes = models.BooleanField(
        "Calculate commutes?", default=True,
        help_text="Commute calculations cost HQ a small amount and take time to complete. "
                  "For 100 ACMs and 10 schools, the cost is $5 and takes about 10 minutes."
    )
    commute_date = models.DateField(
        "Travel date for commute calculations", blank=True, default=get_tomorrow_date,
        help_text="Required if calculating commutes. Choose a date that represents normal traffic."
    )
    commutes_reference_file = models.FileField(
        upload_to=input_upload_path,
        blank=True,
        help_text="After placements are made, you will find a 'Output_Commute_Reference.csv' file in the results. "
                  "If you want to run additional placement processes, "
                  "upload that file here to avoid commute calculation wait time and cost."
    )

    # --- FACTORS --- #
    commute_factor = models.IntegerField("Importance of commute", default=1)
    ethnicity_factor = models.IntegerField("Importance of ethnic diversity", default=1)
    gender_factor = models.IntegerField("Importance of gender diversity", default=1)
    edscore_factor = models.IntegerField("Importance of educational attainment diversity", default=1)
    spanish_factor = models.IntegerField("Importance of matching Spanish speaker targets", default=1)

    # errors
    errors = models.TextField(blank=True)


class PlacementResult(TimeStampedModel, models.Model):
    placementrequest = models.OneToOneField(PlacementRequest, on_delete=models.CASCADE)

    commutes_file = models.FileField(upload_to=output_upload_path)
    placements_file = models.FileField(upload_to=output_upload_path)
    trace_file = models.FileField(upload_to=output_upload_path)

acm_placement_app/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

acm_placement_app/placements/forms.py
from django import forms

from acm_placement_app.placements.models import PlacementRequest
from acm_placement_app.placements.utils import get_acm_survey_missing_columns

RUN_PARAMS_FIELDS = [
    'num_iterations',
    'prevent_roommates',
    'consider_HS_elig',
    'calc_commutes',
    'commute_date',
    'commutes_reference_file',
]

FACTOR_IMPORTANCE_FIELDS = [
    'commute_factor',
    'ethnicity_factor',
    'gender_factor',
    'edscore_factor',
    'spanish_factor',
]

BLANK_COLS_WARNING_MSG = """Warning: the following columns could not be resolved from your survey file. 
These columns will be filled with blanks if you choose to continue:"""


class PlacementRequestSchoolDataForm(forms.ModelForm):
    class Meta:
        model = PlacementRequest
        fields = [
            'school_data_file'
        ]


class PlacementRequestACMSurveyDataForm(forms.ModelForm):

    def get_warnings(self):
        warnings = {}
        _, missing_columns = get_acm_survey_missing_columns(self.files['acm_survey_data_form-acm_survey_data_file'])
        if missing_columns:
            warnings['message'] = BLANK_COLS_WARNING_MSG
            warnings['list'] = missing_columns
        return warnings

    class Meta:
        model = PlacementRequest
        fields = [
            'acm_survey_data_file'
        ]


class PlacementRequestRunParametersForm(forms.ModelForm):
    class Meta:
        model = PlacementRequest
        fields = RUN_PARAMS_FIELDS


class PlacementRequestFactorImportanceForm(forms.ModelForm):
    class Meta:
        model = PlacementRequest
        fields = FACTOR_IMPORTANCE_FIELDS


def get_placementrequest_instance_from_form_list(form_list, commit=True):
    school_data_form, acm_survey_data_form, run_parameters_form, factor_importance_form = form_list
    placementrequest = run_parameters_form.save(commit=False)

    # Uploaded files
    placementrequest.school_data_file = school_data_form.instance.school_data_file
    placementrequest.acm_survey_data_file = acm_survey_data_form.instance.acm_survey_data_file

    # Factor importances
    if factor_importance_form.is_valid():
        for field_name in FACTOR_IMPORTANCE_FIELDS:
            setattr(placementrequest, field_name, factor_importance_form.cleaned_data[field_name])

    if run_parameters_form.is_valid():
        if run_parameters_form.cleaned_data['commutes_reference_file']:
            placementrequest.commute_factor = 0

    if commit:
        placementrequest.save()
    return placementrequest

acm_placement_app/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

acm_placement_app/placements/views.py
import os
import time
import zipfile

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DetailView
from formtools.wizard.views import SessionWizardView

from acm_placement_app.placements.forms import PlacementRequestSchoolDataForm, PlacementRequestACMSurveyDataForm, \
    PlacementRequestRunParametersForm, PlacementRequestFactorImportanceForm, \
    get_placementrequest_instance_from_form_list
from acm_placement_app.placements.models import PlacementRequest
from acm_placement_app.placements.tasks import run_procedure
from acm_placement_app.placements.utils import calculate_cost

FORMS = [
    ('school_data_form', PlacementRequestSchoolDataForm),
    ('acm_survey_data_form', PlacementRequestACMSurveyDataForm),
    ('run_parameters_form', PlacementRequestRunParametersForm),
    ('factor_importance_form', PlacementRequestFactorImportanceForm),
]

TEMPLATES = {
    'school_data_form': "wizard/school_data_form.html",
    'acm_survey_data_form': "wizard/acm_survey_data_form.html",
    'run_parameters_form': "wizard/run_parameters_form.html",
    'factor_importance_form': "wizard/factor_importance_form.html"
}


@method_decorator(login_required, name='dispatch')
class PlacementRequestWizard(SessionWizardView):
    form_list = FORMS
    file_storage = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'tmp', 'wizard'))

    def get_template_names(self):
        return [TEMPLATES[self.steps.current]]

    def get_context_data(self, form, **kwargs):
        context = super().get_context_data(form=form, **kwargs)
        current_step = self.steps.current
        if current_step == 'run_parameters_form':
            acm_survey_data_form = self.get_form(step='acm_survey_data_form',
                                                 data=self.storage.get_step_data('acm_survey_data_form'),
                                                 files=self.storage.get_step_files('acm_survey_data_form'))
            context['warnings'] = acm_survey_data_form.get_warnings()

        return context

    def done(self, form_list, **kwargs):
        placementrequest = get_placementrequest_instance_from_form_list(form_list, commit=False)
        placementrequest.requested_by = self.request.user
        if not placementrequest.calc_commutes:
            placementrequest.commute_factor = 0
        placementrequest.save()
        return HttpResponseRedirect(reverse('placements:run', kwargs={'id': placementrequest.id}))


@method_decorator(login_required, name='dispatch')
class RunView(View):
    def get(self, request, id):
        placementrequest = PlacementRequest.objects.get(id=id)

        if placementrequest.is_successful:
            return render(request, "wizard/is_successful.html", context={'placementrequest': placementrequest})

        return render(request, "wizard/run.html", context=calculate_cost(placementrequest))

    def post(self, request, id):
        placementrequest = PlacementRequest.objects.get(id=id)

        if placementrequest.is_successful:
            return render(request, "wizard/is_successful.html", context={'placementrequest': placementrequest})

        placementrequest.started = timezone.now()
        placementrequest.save()

        run_procedure.delay(id, started=placementrequest.started)
        return render(request, "wizard/done.html", context={'placementrequest': placementrequest})


@method_decorator(login_required, name='dispatch')
class PlacementRequestList(ListView):
    context_object_name = 'placementrequests'
    template_name = "placements/request_list.html"
    queryset = PlacementRequest.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(requested_by=self.request.user)


@method_decorator(login_required, name='dispatch')
class PlacementRequestDetail(DetailView):
    context_object_name = 'placementrequest'
    template_name = "placements/request_detail.html"
    queryset = PlacementRequest.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(requested_by=self.request.user)


@login_required
def download_results(request, pk=None):
    placementrequest = PlacementRequest.objects.get(id=pk)

    if not placementrequest.is_successful:
        raise Http404

    placementresult = placementrequest.placementresult
    response = HttpResponse(content_type='application/zip')
    zip_file_name = f"Request_{placementrequest.id}_results.zip"
    response['Content-Disposition'] = f'attachment; filename={zip_file_name}'

    with zipfile.ZipFile(response, 'w') as zip_file:
        write_file_to_zip(zip_file, placementrequest.school_data_file)
        write_file_to_zip(zip_file, placementrequest.acm_survey_data_file)
        write_file_to_zip(zip_file, placementresult.commutes_file)
        write_file_to_zip(zip_file, placementresult.placements_file)
        write_file_to_zip(zip_file, placementresult.trace_file)

    return response


def write_file_to_zip(zip_file, file_obj):
    file_name = os.path.basename(file_obj.name)
    zip_file.writestr(file_name, file_obj.read())

acm_placement_app/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

acm_placement_app/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

acm_placement_app/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}City Year ACM School Placement{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="An algorithm to match City Year AmeriCorps Members to schools based on various characteristics of each">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <!-- Favicon Info -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicons/apple-touch-icon.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicons/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicons/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicons/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'favicons/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
    <style>
      .container {
        margin-top: 2em;
      }
    </style>
    {% endblock %}

  </head>

  <body>
    {% block navbar %}
      <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">ACM Placement App</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              {% if request.user.is_superuser %}
                <li class="nav-item">
                  <a target="_blank" class="nav-link" href="{% url 'admin:index' %}">{% trans "Admin" %}</a>
                </li>
              {% endif %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'placements:placementrequest-list' %}">
                  {% trans "My Requests" %}
                </a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>
    {% endblock %}

    {% block header %}
        {% include "header.html" %}
    {% endblock %}
    <div class="container">
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->
    <footer></footer>

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 

acm_placement_app/templates/header.html
{% load staticfiles %}
<div class="cy-headerbar">
  <div class="cy-header">
    <img class="cy-logo" src="{% static 'placements/cypatch_125px_8.png' %}" alt="City Year">
    <div class="cy-logo-title"><a href="/" style="color: black; text-decoration:none;">AmeriCorps Member<br/>School Placement</a></div>
    <img class="cy-icon" src="{% static 'placements/image46.png' %}" width="58">
  </div>
</div>