acm_placement_app/placements/urls.py
from django.urls import path

from acm_placement_app.placements.views import PlacementRequestWizard, RunView, PlacementRequestList, \
    PlacementRequestDetail, download_results

app_name = 'placements'

urlpatterns = [
    path("request/", PlacementRequestWizard.as_view(), name='request-placements'),
    path("run/<int:id>/", RunView.as_view(), name='run'),
    path("list/", PlacementRequestList.as_view(), name='placementrequest-list'),
    path("<int:pk>/", PlacementRequestDetail.as_view(), name='placementrequest-details'),
    path("<int:pk>/download-results", download_results, name='placementrequest-download-results'),
]

acm_placement_app/users/urls.py
from django.urls import path

from acm_placement_app.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("acm_placement_app.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Your stuff: custom urls includes go here
urlpatterns += [
    path("placements/", include("acm_placement_app.placements.urls", namespace="placements")),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

acm_placement_app/placements/models.py
import datetime
import os

from django.conf import settings
from django.db import models
from model_utils.models import TimeStampedModel

NOT_STARTED = 'not_started'
STARTED = 'started'
FAILURE = 'failure'
SUCCESS = 'success'


def get_tomorrow_date():
    return datetime.date.today() + datetime.timedelta(days=1)


def input_upload_path(instance, filename):
    return os.path.join("data", 'inputs', filename)


def output_upload_path(instance, filename):
    return os.path.join("data", 'outputs', filename)


class PlacementRequest(TimeStampedModel, models.Model):
    requested_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, blank=True, null=True)
    started = models.DateTimeField(blank=True, null=True, editable=False)
    completed = models.DateTimeField(blank=True, null=True, editable=False)

    @property
    def is_completed(self):
        return self.completed is not None

    @property
    def is_successful(self):
        return PlacementResult.objects.filter(placementrequest=self).exists()

    @property
    def run_duration(self):
        if self.is_completed:
            return self.completed - self.started

    @property
    def run_state(self):
        if self.started is None:
            return NOT_STARTED
        if self.started and self.completed is None:
            return STARTED
        if self.started and self.completed and not self.is_successful:
            return FAILURE
        if self.started and self.completed and self.is_successful:
            return SUCCESS

    school_data_file = models.FileField(upload_to=input_upload_path)
    acm_survey_data_file = models.FileField("ACM survey data file", upload_to=input_upload_path)

    num_iterations = models.IntegerField(
        "Number of iterations", default=10000,
        help_text="The number of team placements that will be attempted. 10,000 or more is recommended."
    )
    prevent_roommates = models.BooleanField("Prevent roommates from serving on the same team?", default=True)
    consider_HS_elig = models.BooleanField(
        "Apply High School eligibility rule?", default=True,
        help_text="ACMs are eligible to serve in High School if they are 21+ years old (or have college experience) "
                  "and are confident tutoring at least algebra-level math."
    )

    calc_commutes = models.BooleanField(
        "Calculate commutes?", default=True,
        help_text="Commute calculations cost HQ a small amount and take time to complete. "
                  "For 100 ACMs and 10 schools, the cost is $5 and takes about 10 minutes."
    )
    commute_date = models.DateField(
        "Travel date for commute calculations", blank=True, default=get_tomorrow_date,
        help_text="Required if calculating commutes. Choose a date that represents normal traffic."
    )
    commutes_reference_file = models.FileField(
        upload_to=input_upload_path,
        blank=True,
        help_text="After placements are made, you will find a 'Output_Commute_Reference.csv' file in the results. "
                  "If you want to run additional placement processes, "
                  "upload that file here to avoid commute calculation wait time and cost."
    )

    # --- FACTORS --- #
    commute_factor = models.IntegerField("Importance of commute", default=1)
    ethnicity_factor = models.IntegerField("Importance of ethnic diversity", default=1)
    gender_factor = models.IntegerField("Importance of gender diversity", default=1)
    edscore_factor = models.IntegerField("Importance of educational attainment diversity", default=1)
    spanish_factor = models.IntegerField("Importance of matching Spanish speaker targets", default=1)

    # errors
    errors = models.TextField(blank=True)


class PlacementResult(TimeStampedModel, models.Model):
    placementrequest = models.OneToOneField(PlacementRequest, on_delete=models.CASCADE)

    commutes_file = models.FileField(upload_to=output_upload_path)
    placements_file = models.FileField(upload_to=output_upload_path)
    trace_file = models.FileField(upload_to=output_upload_path)

acm_placement_app/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

acm_placement_app/placements/forms.py
from django import forms

from acm_placement_app.placements.models import PlacementRequest
from acm_placement_app.placements.utils import get_acm_survey_missing_columns

RUN_PARAMS_FIELDS = [
    'num_iterations',
    'prevent_roommates',
    'consider_HS_elig',
    'calc_commutes',
    'commute_date',
    'commutes_reference_file',
]

FACTOR_IMPORTANCE_FIELDS = [
    'commute_factor',
    'ethnicity_factor',
    'gender_factor',
    'edscore_factor',
    'spanish_factor',
]

BLANK_COLS_WARNING_MSG = """Warning: the following columns could not be resolved from your survey file. 
These columns will be filled with blanks if you choose to continue:"""


class PlacementRequestSchoolDataForm(forms.ModelForm):
    class Meta:
        model = PlacementRequest
        fields = [
            'school_data_file'
        ]


class PlacementRequestACMSurveyDataForm(forms.ModelForm):

    def get_warnings(self):
        warnings = {}
        _, missing_columns = get_acm_survey_missing_columns(self.files['acm_survey_data_form-acm_survey_data_file'])
        if missing_columns:
            warnings['message'] = BLANK_COLS_WARNING_MSG
            warnings['list'] = missing_columns
        return warnings

    class Meta:
        model = PlacementRequest
        fields = [
            'acm_survey_data_file'
        ]


class PlacementRequestRunParametersForm(forms.ModelForm):
    class Meta:
        model = PlacementRequest
        fields = RUN_PARAMS_FIELDS


class PlacementRequestFactorImportanceForm(forms.ModelForm):
    class Meta:
        model = PlacementRequest
        fields = FACTOR_IMPORTANCE_FIELDS


def get_placementrequest_instance_from_form_list(form_list, commit=True):
    school_data_form, acm_survey_data_form, run_parameters_form, factor_importance_form = form_list
    placementrequest = run_parameters_form.save(commit=False)

    # Uploaded files
    placementrequest.school_data_file = school_data_form.instance.school_data_file
    placementrequest.acm_survey_data_file = acm_survey_data_form.instance.acm_survey_data_file

    # Factor importances
    if factor_importance_form.is_valid():
        for field_name in FACTOR_IMPORTANCE_FIELDS:
            setattr(placementrequest, field_name, factor_importance_form.cleaned_data[field_name])

    if run_parameters_form.is_valid():
        if run_parameters_form.cleaned_data['commutes_reference_file']:
            placementrequest.commute_factor = 0

    if commit:
        placementrequest.save()
    return placementrequest

acm_placement_app/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

acm_placement_app/placements/views.py
import os
import time
import zipfile

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DetailView
from formtools.wizard.views import SessionWizardView

from acm_placement_app.placements.forms import PlacementRequestSchoolDataForm, PlacementRequestACMSurveyDataForm, \
    PlacementRequestRunParametersForm, PlacementRequestFactorImportanceForm, \
    get_placementrequest_instance_from_form_list
from acm_placement_app.placements.models import PlacementRequest
from acm_placement_app.placements.tasks import run_procedure
from acm_placement_app.placements.utils import calculate_cost

FORMS = [
    ('school_data_form', PlacementRequestSchoolDataForm),
    ('acm_survey_data_form', PlacementRequestACMSurveyDataForm),
    ('run_parameters_form', PlacementRequestRunParametersForm),
    ('factor_importance_form', PlacementRequestFactorImportanceForm),
]

TEMPLATES = {
    'school_data_form': "wizard/school_data_form.html",
    'acm_survey_data_form': "wizard/acm_survey_data_form.html",
    'run_parameters_form': "wizard/run_parameters_form.html",
    'factor_importance_form': "wizard/factor_importance_form.html"
}


@method_decorator(login_required, name='dispatch')
class PlacementRequestWizard(SessionWizardView):
    form_list = FORMS
    file_storage = FileSystemStorage(location=os.path.join(settings.MEDIA_ROOT, 'tmp', 'wizard'))

    def get_template_names(self):
        return [TEMPLATES[self.steps.current]]

    def get_context_data(self, form, **kwargs):
        context = super().get_context_data(form=form, **kwargs)
        current_step = self.steps.current
        if current_step == 'run_parameters_form':
            acm_survey_data_form = self.get_form(step='acm_survey_data_form',
                                                 data=self.storage.get_step_data('acm_survey_data_form'),
                                                 files=self.storage.get_step_files('acm_survey_data_form'))
            context['warnings'] = acm_survey_data_form.get_warnings()

        return context

    def done(self, form_list, **kwargs):
        placementrequest = get_placementrequest_instance_from_form_list(form_list, commit=False)
        placementrequest.requested_by = self.request.user
        if not placementrequest.calc_commutes:
            placementrequest.commute_factor = 0
        placementrequest.save()
        return HttpResponseRedirect(reverse('placements:run', kwargs={'id': placementrequest.id}))


@method_decorator(login_required, name='dispatch')
class RunView(View):
    def get(self, request, id):
        placementrequest = PlacementRequest.objects.get(id=id)

        if placementrequest.is_successful:
            return render(request, "wizard/is_successful.html", context={'placementrequest': placementrequest})

        return render(request, "wizard/run.html", context=calculate_cost(placementrequest))

    def post(self, request, id):
        placementrequest = PlacementRequest.objects.get(id=id)

        if placementrequest.is_successful:
            return render(request, "wizard/is_successful.html", context={'placementrequest': placementrequest})

        placementrequest.started = timezone.now()
        placementrequest.save()

        run_procedure.delay(id, started=placementrequest.started)
        return render(request, "wizard/done.html", context={'placementrequest': placementrequest})


@method_decorator(login_required, name='dispatch')
class PlacementRequestList(ListView):
    context_object_name = 'placementrequests'
    template_name = "placements/request_list.html"
    queryset = PlacementRequest.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(requested_by=self.request.user)


@method_decorator(login_required, name='dispatch')
class PlacementRequestDetail(DetailView):
    context_object_name = 'placementrequest'
    template_name = "placements/request_detail.html"
    queryset = PlacementRequest.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(requested_by=self.request.user)


@login_required
def download_results(request, pk=None):
    placementrequest = PlacementRequest.objects.get(id=pk)

    if not placementrequest.is_successful:
        raise Http404

    placementresult = placementrequest.placementresult
    response = HttpResponse(content_type='application/zip')
    zip_file_name = f"Request_{placementrequest.id}_results.zip"
    response['Content-Disposition'] = f'attachment; filename={zip_file_name}'

    with zipfile.ZipFile(response, 'w') as zip_file:
        write_file_to_zip(zip_file, placementrequest.school_data_file)
        write_file_to_zip(zip_file, placementrequest.acm_survey_data_file)
        write_file_to_zip(zip_file, placementresult.commutes_file)
        write_file_to_zip(zip_file, placementresult.placements_file)
        write_file_to_zip(zip_file, placementresult.trace_file)

    return response


def write_file_to_zip(zip_file, file_obj):
    file_name = os.path.basename(file_obj.name)
    zip_file.writestr(file_name, file_obj.read())

acm_placement_app/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

acm_placement_app/templates/wizard/acm_survey_data_file.html
{% extends 'wizard/wizard_form.html' %}

{% block step_name %}
  ACM Survey Data
{% endblock %}

{% block help %}
  <p>Before uploading your survey data, ensure your survey results are clean:</p>
  <ol>
    <li>Check that no ACM took the survey twice.</li>
    <li>If two ACMs have the same full name, make each name unique (i.e. John Smith1, John Smith2).</li>
    <li>Ensure your column names match the expected values in <a href='https://github.com/chrisluedtke/ACM-School-Placement/blob/master/webapp/Survey%20Items%20to%20Variable%20Names.xlsx?raw=true'>this spreadsheet</a>. If used the SurveyGizmo survey provided by HQ, your column names will be converted automatically.</li>
    <li>Determine whether any ACMs should be specifically placed at a certain school (e.g. ACMs with accessibility needs, specific language abilities, or those who attended a school themselves as a student). Add a column named "Manual.Placement" to your survey results and type in any school as it appears in your School Data spreadsheet from Step 1. This guarantees that the ACM is placed at the given school.</li>
  </ol>

  <p>Upload your survey data file (.csv) and continue.</p>
{% endblock %}

acm_placement_app/templates/wizard/acm_survey_data_form.html
{% extends 'wizard/wizard_form.html' %}

{% block step_name %}
  ACM Survey Data
{% endblock %}

{% block help %}
  <p>Before uploading your survey data, ensure your survey results are clean:</p>
  <ol>
    <li>Check that no ACM took the survey twice.</li>
    <li>If two ACMs have the same full name, make each name unique (i.e. John Smith1, John Smith2).</li>
    <li>Ensure your column names match the expected values in <a href='https://github.com/chrisluedtke/ACM-School-Placement/blob/master/webapp/Survey%20Items%20to%20Variable%20Names.xlsx?raw=true'>this spreadsheet</a>. If used the SurveyGizmo survey provided by HQ, your column names will be converted automatically.</li>
    <li>Determine whether any ACMs should be specifically placed at a certain school (e.g. ACMs with accessibility needs, specific language abilities, or those who attended a school themselves as a student). Add a column named "Manual.Placement" to your survey results and type in any school as it appears in your School Data spreadsheet from Step 1. This guarantees that the ACM is placed at the given school.</li>
  </ol>

  <p>Upload your survey data file (.csv) and continue.</p>
{% endblock %}

acm_placement_app/templates/wizard/base.html
{% extends "base.html" %}
{% load staticfiles %}

acm_placement_app/templates/wizard/done.html
{% extends "wizard/base.html" %}

{% block content %}
  <p>Placements are being made. You can see the results
    <a href="{% url 'placements:placementrequest-details' placementrequest.id %}">
      here
    </a>
    once they are ready.
  </p>
{% endblock %}

acm_placement_app/templates/wizard/factor_importance_form.html
{% extends 'wizard/wizard_form.html' %}

{% block step_name %}
  Factor Importance
{% endblock %}

{% block help %}
  <p>Set any factor to 0 to remove it from consideration. Set it to 2 or 3 to place greater weight on that factor.</p>
{% endblock %}

acm_placement_app/templates/wizard/is_completed.html
{% extends "wizard/base.html" %}

{% block content %}
  <p>Placements are already calculated. You can see the results
    <a href="{% url 'placements:placementrequest-details' placementrequest.id %}">
      here
    </a>
  </p>
{% endblock %}

acm_placement_app/templates/wizard/is_successful.html
{% extends "wizard/base.html" %}

{% block content %}
  <p>Placements are already calculated. You can see the results
    <a href="{% url 'placements:placementrequest-details' placementrequest.id %}">
      here
    </a>
  </p>
{% endblock %}

acm_placement_app/templates/wizard/run.html
{% extends "wizard/base.html" %}

{% block content %}
    <h3>Run Placements</h3>

    <p>
      You are placing <strong>{{ n_acms }} ACMs</strong> on <strong>{{ n_schools }} teams</strong>{{ and_text }}.
      This will take about <strong>{{run_time_mins}} minutes</strong>{{ and_cost_text }}<strong>{{ and_cost }}</strong>.
      There is a firm runtime limit of 120 minutes.
    </p>

    <p>
      When you are ready, click "Run Placements" only once.
      The process will begin as soon as you press the button.
    </p>

    <form method="post">
      {% csrf_token %}
      <div class="form-group">
        <button type="submit" class="btn btn-success">Run Placements</button>
      </div>
    </form>
{% endblock %}

acm_placement_app/templates/wizard/run_parameters_form.html
{% extends 'wizard/wizard_form.html' %}

{% block step_name %}
  Set Options
{% endblock %}

{% block help %}
  <p>Choose your options for how placements are made.</p>
{% endblock %}

acm_placement_app/templates/wizard/school_data_form.html
{% extends 'wizard/wizard_form.html' %}

{% block step_name %}
  School Data
{% endblock %}

{% block help %}
  <p>
    Download the Excel template below and fill in the columns.
    View comments on the column headers to learn how each column affects the placement process.
  </p>

  <a href="https://github.com/mrklees/acm-placement-app/raw/master/dummy_inputs/ACM_Placement_School_Data.xlsx"
     class="btn btn-light"
  >
    Download School Data Template
  </a>

  <p>After you have filled in the template, upload the file and continue.</p>
{% endblock %}

acm_placement_app/templates/wizard/wizard_form.html
{% extends "base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block head %}
  {{ wizard.form.media }}
{% endblock %}

{% block content %}
  {% if warnings %}
    <div class="alert alert-warning" role="alert">
      <p>{{ warnings.message }}</p>
      <ul>
        {% for item in warnings.list %}
          <li>{{ item }}</li>
        {% endfor %}
      </ul>
      <form method="post">{% csrf_token %}
        <p>
          You can choose to go back and re-upload the survey file.
          If you'd like to continue, scroll down and fill the rest of the form
        </p>
        <button class="btn btn-secondary"
                name="wizard_goto_step"  type="submit" value="{{ wizard.steps.prev }}"
                onclick="return confirm('Are you sure you want to to go back?');"
        >
          {% trans "Back" %}
        </button>
      </form>
    </div>
  {% endif %}

  <h3 id="header">Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}: {% block step_name %}{% endblock %}</h3>

  {% block help %}{% endblock %}

  <form method="post" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    <div>
      {{ wizard.management_form }}
      {% if wizard.form.forms %}
        {{ wizard.form.management_form }}
        {% for form in wizard.form.forms %}
            {{ form|crispy }}
        {% endfor %}
      {% else %}
        {{ wizard.form|crispy }}
      {% endif %}
    </div>
    <div class="form-buttons">
      {% if wizard.steps.current == wizard.steps.last %}
        <input type="submit" class="btn btn-success float-right" value="{% trans "Submit" %}"/>
      {% else %}
        <input type="submit" class="btn btn-primary float-right" value="{% trans "Next" %}"/>
      {% endif %}

      {% if wizard.steps.prev %}
        <button class="btn btn-danger"
                name="wizard_goto_step"  type="submit" value="{{ wizard.steps.first }}"
                onclick="return confirm('Are you sure you want reset this form?');"
        >
          {% trans "Go to beginning" %}
        </button>
        <button class="btn btn-secondary"
                name="wizard_goto_step" type="submit" value="{{ wizard.steps.prev }}"
                onclick="return confirm('Are you sure you want to to go back?');"
        >
          {% trans "Back" %}
        </button>

      {% endif %}
    </div>
  </form>
{% endblock %}